services:
  db:
    image: postgres:15
    container_name: examen_ci_cd
    environment:
      POSTGRES_DB: Myapp_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app:create_app
      - FLASK_RUN_HOST=0.0.0.0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=Myapp_base
      - DB_USER=postgres
      - DB_PASSWORD=root
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

volumes:
  db_data: